on:
  push:
    branches: [ "master" ]
  pull_request:
    branches: [ "master" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Test
        run: ls
        shell: bash
      - name: "Doxygen!"
        uses: mattnotmitt/doxygen-action@1.9.5
        with:
          working-directory: .
